### ISSUE TITLE
Critical Dr.Jit compiler failure: cuda_check(): API error 0718 (CUDA_ERROR_INVALID_PC): "invalid program counter" in D:\a\drjit\drjit\ext\drjit-core\src\eval.cpp:395

### ISSUE THREAD

**Issue by aantg** [mitsuba-renderer/drjit#296]
Hello. Got this error after updating NVIDIA driver to latest version 565.90 even with "[Hello World](https://mitsuba.readthedocs.io/en/stable/index.html#hello-world)" example from Mitsuba3 documentation (using 'cuda_ad_rgb' variant of course). Rolling back to previous driver version (561.09) make this error disappear.

Looks like there's some incompatibility?

DrJit 0.4.6 + mitsuba 3.5.2

**Comment by njroussel** [comment]
Hi @aantg 

What OS and GPU model are you using?

In my personal experience these type of errors are often related to a faulty driver installation.

**Comment by tatue64** [comment]
Can confirm this on Manjaro Linux, NVIDIA driver 565.57.01, cuda 12.6.2 (but downgrading cuda did not help). 

This error occurs with drjit 0.4.6 and Mitsuba 3.5.2, but also with drjit 1.0.0 in the current development version Mitsuba 3.6 when compiled in Release mode (clang). "llmv_ad_rgb" always works.  Somewhat surprisingly, the error does *not* occur if the program is compiled in Debug mode. 

In the latter case (Mitsuba 3.6) the tutorial scene from the "scripting a renderer" notebook works with "cuda_ad_rgb", but fails, for example, when the "diffuse" material is replaced with "roughplastic".

This may be a driver problem (as far as I know, this is a beta driver), but the dependence of the error on the compilation mode and the dependence on scene parameters suggest a problem with drjit.

**Comment by Kyriota** [comment]
I have also encountered this problem:

`Critical Dr.Jit compiler failure: cuda_check(): API error 0718 (CUDA_ERROR_INVALID_PC): "invalid program counter" in D:\a\drjit\drjit\ext\drjit-core\src\eval.cpp:395.`

Env:

Platform: Windows 11
Python Ver: 3.10.0
Mitsuba Ver: 3.5.0
Dr Jit Ver: 0.4.4
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Oct_30_01:18:48_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.6, V12.6.85
Build cuda_12.6.r12.6/compiler.35059454_0
```
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.90                 Driver Version: 565.90         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080      WDDM  |   00000000:01:00.0  On |                  N/A |
|  0%   46C    P8             14W /  320W |    1097MiB /  16376MiB |      5%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

**Comment by tatue64** [comment]
This problem is related to the NVIDIA driver version 565, not to the mitsuba 3.x version, cuda version, compiler, linux kernel etc. For me, only downgrading this driver (in my case to 550.135) helped. Version 560 does probably also work. 

Maybe simply a bug in the beta driver, but maybe also an incompatibility of drjit with new procedure implemented in newer driver.

**Comment by devmdxac** [comment]
Hello,

It indeed seems to work now (even if I did not test many tutorials, the one that did not run correctly before downgrading are now working as expected). Thank you very much. 

I for sure did not downgrade the driver correctly before and probably introduce issues when trying to build Mitsuba. 

The Nvidia driver version I am currently using is 560.35.03.

Thank you again for your help. 

Best wishes

**Comment by xacond00** [comment]
This is a critical issue, yet nobody talks about it. Downgrading drivers isn't always an option.

**Comment by wjakob** [comment]
Dear all -- this is a serious problem indeed. But I don't think this is our fault—a change made between NVIDIA driver version 561 and 565.9 causes a miscompilation of very simple programs.

I filed a reproducer with NVIDIA. But even if this is fixed in an upcoming release, I don't think that we will be able to work around it for the existing drivers. If so, we will likely push out a new release of Dr.Jit that just errors out with an error message telling the user to install a newer or older driver.

**Comment by wjakob** [comment]
The R570 driver version is available now, which fixes this issue. I will close the PR.
